# Generated by Django 2.2.7 on 2019-11-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='People',
        ),
    ]
